version: '3'
services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: "curl -f http://localhost:9000/minio/health/live"
      interval: 30s
      timeout: 5s
      retries: 5
  db:
    image: postgres:alpine3.19
    restart: always
    environment:
      POSTGRES_PASSWORD: "PROD"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    healthcheck:
      test: "pg_isready -d PROD -U postgres"
      interval: 5s
      timeout: 60s
      retries: 20
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  article54:
    build: ./article54
    depends_on:
      minio:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      PORT: 8080
      HOST: "0.0.0.0"
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: PROD
      DB_NAME: postgres
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      LOGIN_CHECK: "http://backend:8080/login-check"
  backend:
    build: ./server
    environment:
      PORT: 8080
      HOST: "0.0.0.0"
      ARTICLE54: "http://article54:8080"
volumes:
  db-data:
  minio_data: